name: Release Notification

on:
  release:
    types: [published]

jobs:
  send-slack-notification:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Log Message
        run: echo "Hello, this is a log message!"
