name: Release To NuGet
run-name: Publishing Package Version ${{ github.event.inputs.Version }}
on:
  workflow_dispatch:
    inputs:
      Version:
        description: "This input field requires version in format: x.y.z, where x => major version, y => minor version and z => patch version"
        required: true
jobs:
  create-release:
    name: Creating release version ${{ github.event.inputs.Version }}
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - uses: actions/checkout@v3

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.event.inputs.Version }}
          name: Release Version ${{ github.event.inputs.Version }}
          body: ${{ github.event.inputs.Version }}
