name: Release Notification

on:
  workflow_run:
    workflows: ["Release To NuGet"]
    types: [in_progress]

jobs:
  send-slack-notification:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Log Message
        run: echo "Hello, this is a log message!"
